### ISSUE TITLE
Have the default colours of the faces handle light/dark modes in GNU Emacs

### ISSUE THREAD

**Issue by a5corpii** [davep/fasta.el#1]
Thanks Dave for your fasta.el!

I used this package in my spacemacs for reviewing some seq results, but in my opinion, the default color may not very comfortable. As the default theme of my emacs is dark style, there is no strong contrast between adenine face with the background, while the guanine and thymine face is less noticeable after switching to the light style theme.

I would like to propose that the "#8dd4e8" could be used as the default blue for dark theme and "#4b5cc4" (or "#065279") for the light theme.
"#3de1ad" and "#057748" used as green color for dark and light theme respectively.
……

Or, I think it's a good feature to be able to customize the colors.

**Comment by davep** [comment]
All of the faces used in `fasta.el` are defined with `defface` and are part of the customize group `fasta`. So you only need to do:

<kbd>M-x</kbd> `customize-group` <kbd>RET</kbd> `fasta` <kbd>RET</kbd>

and you can customize all of the faces to best suit your chosen theme:

![Screenshot 2019-03-16 at 13 56 45](https://user-images.githubusercontent.com/28237/54476314-a73e1700-47f3-11e9-8d29-6a114b9910d7.png)

I'm not aware of a method of knowing if a "light" or "dark" theme is in use, and adapting to it accordingly; but I'll do some checking to see if that's actually a thing in GNU Emacs. A very quick look (looking at the definition of `font-lock-comment-face`) suggests there is something, so I think I have some reading to do.

**Comment by a5corpii** [comment]
Thank you,
I had customized the colors in function `custom-set-faces`, as I didn't write the correct elisp earlier today.

**Comment by davep** [comment]
Right, I think I see how to handle light vs dark themes, when specifying default faces (see 3c83570e9e25735d46c76fac7fd828702df11fb3). Next up: actually plugging in the better colour choices.

Thanks for this, I've learnt a new thing about GNU Emacs today (being using it, writing for it, and contributing to it since 1995 and there's *still* stuff to learn! :D).

**Comment by davep** [comment]
[v1.0](https://github.com/davep/fasta.el/releases/tag/v1.0) should, I think, work better for you. I've tweaked the colours a little, and the main change is that most faces now support colours for both dark and light themes.

Hopefully this will help.

Thanks again for letting me know about this; I've learnt a handy thing today. :)
